/**
 * CIVIC SUITE: Demo Data
 * 
 * In-memory demo data for the Civic Suite.
 * Simulates an Estate Management Association (Nigerian context).
 */

import {
  Constituent,
  DuesRecord,
  ServiceRequest,
  Certificate,
  CivicEvent,
  Poll,
  Vote,
  generateMemberNumber,
  generateTicketNumber,
  generateCertificateNumber,
  generateVerificationCode,
} from './config';

// ============================================================================
// DEMO TENANT ID (matches demo-school for testing purposes)
// ============================================================================

const DEMO_TENANT_ID = 'demo-civic';

// ============================================================================
// DEMO CONSTITUENTS (Members)
// ============================================================================

export const DEMO_CONSTITUENTS: Constituent[] = [
  {
    id: 'const_001',
    tenantId: DEMO_TENANT_ID,
    memberNumber: 'MEM-2020-0001',
    firstName: 'Adebayo',
    lastName: 'Okonkwo',
    email: 'adebayo.okonkwo@email.com',
    phone: '08012345678',
    membershipType: 'LANDLORD',
    membershipStatus: 'ACTIVE',
    ward: 'Ward A',
    zone: 'Zone 1',
    unit: 'Block 5',
    block: 'Plot 15',
    propertyType: 'RESIDENTIAL',
    propertyAddress: 'Plot 15, Block 5, Harmony Estate',
    householdSize: 5,
    occupation: 'Engineer',
    registrationDate: '2020-03-15',
    lastContributionDate: '2025-01-01',
    totalContributions: 450000,
    outstandingBalance: 0,
    createdAt: '2020-03-15T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'const_002',
    tenantId: DEMO_TENANT_ID,
    memberNumber: 'MEM-2021-0045',
    firstName: 'Ngozi',
    lastName: 'Eze',
    email: 'ngozi.eze@email.com',
    phone: '08098765432',
    membershipType: 'RESIDENT',
    membershipStatus: 'ACTIVE',
    ward: 'Ward A',
    zone: 'Zone 1',
    unit: 'Block 3',
    block: 'Plot 8',
    propertyType: 'RESIDENTIAL',
    propertyAddress: 'Plot 8, Block 3, Harmony Estate',
    householdSize: 3,
    occupation: 'Banker',
    registrationDate: '2021-06-20',
    lastContributionDate: '2024-12-15',
    totalContributions: 180000,
    outstandingBalance: 15000,
    createdAt: '2021-06-20T10:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },
  {
    id: 'const_003',
    tenantId: DEMO_TENANT_ID,
    memberNumber: 'MEM-2019-0012',
    firstName: 'Chukwuemeka',
    lastName: 'Nnamdi',
    email: 'chukwuemeka.n@email.com',
    phone: '08055544433',
    membershipType: 'LANDLORD',
    membershipStatus: 'ACTIVE',
    ward: 'Ward B',
    zone: 'Zone 2',
    unit: 'Block 10',
    block: 'Plot 22',
    propertyType: 'RESIDENTIAL',
    propertyAddress: 'Plot 22, Block 10, Harmony Estate',
    householdSize: 6,
    occupation: 'Business Owner',
    registrationDate: '2019-01-10',
    lastContributionDate: '2025-01-03',
    totalContributions: 720000,
    outstandingBalance: 0,
    createdAt: '2019-01-10T10:00:00Z',
    updatedAt: '2025-01-03T10:00:00Z',
  },
  {
    id: 'const_004',
    tenantId: DEMO_TENANT_ID,
    memberNumber: 'MEM-2022-0078',
    firstName: 'Fatima',
    lastName: 'Ibrahim',
    email: 'fatima.ibrahim@email.com',
    phone: '08033322211',
    membershipType: 'TENANT',
    membershipStatus: 'ACTIVE',
    ward: 'Ward A',
    zone: 'Zone 1',
    unit: 'Block 2',
    block: 'Plot 5',
    propertyType: 'RESIDENTIAL',
    propertyAddress: 'Plot 5, Block 2, Harmony Estate',
    householdSize: 2,
    occupation: 'Teacher',
    registrationDate: '2022-09-01',
    lastContributionDate: '2024-11-30',
    totalContributions: 90000,
    outstandingBalance: 30000,
    createdAt: '2022-09-01T10:00:00Z',
    updatedAt: '2024-11-30T10:00:00Z',
  },
  {
    id: 'const_005',
    tenantId: DEMO_TENANT_ID,
    memberNumber: 'MEM-2020-0023',
    firstName: 'Oluwaseun',
    lastName: 'Adeleke',
    email: 'seun.adeleke@email.com',
    phone: '08077788899',
    membershipType: 'LANDLORD',
    membershipStatus: 'SUSPENDED',
    ward: 'Ward C',
    zone: 'Zone 3',
    unit: 'Block 15',
    block: 'Plot 30',
    propertyType: 'COMMERCIAL',
    propertyAddress: 'Plot 30, Block 15, Harmony Estate',
    householdSize: 0,
    occupation: 'Shop Owner',
    registrationDate: '2020-05-15',
    lastContributionDate: '2024-06-30',
    totalContributions: 200000,
    outstandingBalance: 120000,
    createdAt: '2020-05-15T10:00:00Z',
    updatedAt: '2024-06-30T10:00:00Z',
  },
  {
    id: 'const_006',
    tenantId: DEMO_TENANT_ID,
    memberNumber: 'MEM-2023-0156',
    firstName: 'Amara',
    lastName: 'Obi',
    email: 'amara.obi@email.com',
    phone: '08066655544',
    membershipType: 'RESIDENT',
    membershipStatus: 'ACTIVE',
    ward: 'Ward B',
    zone: 'Zone 2',
    unit: 'Block 8',
    block: 'Plot 18',
    propertyType: 'RESIDENTIAL',
    propertyAddress: 'Plot 18, Block 8, Harmony Estate',
    householdSize: 4,
    occupation: 'Doctor',
    registrationDate: '2023-02-28',
    lastContributionDate: '2025-01-02',
    totalContributions: 75000,
    outstandingBalance: 0,
    createdAt: '2023-02-28T10:00:00Z',
    updatedAt: '2025-01-02T10:00:00Z',
  },
];

// ============================================================================
// DEMO DUES RECORDS
// ============================================================================

export const DEMO_DUES: DuesRecord[] = [
  {
    id: 'dues_001',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_001',
    constituentName: 'Adebayo Okonkwo',
    duesType: 'SERVICE_CHARGE',
    amount: 15000,
    dueDate: '2025-01-31',
    status: 'PAID',
    paidAmount: 15000,
    paidDate: '2025-01-01',
    receiptNumber: 'RCP-2025-0001',
    period: 'January 2025',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'dues_002',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_002',
    constituentName: 'Ngozi Eze',
    duesType: 'SERVICE_CHARGE',
    amount: 15000,
    dueDate: '2025-01-31',
    status: 'PENDING',
    paidAmount: 0,
    period: 'January 2025',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'dues_003',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_003',
    constituentName: 'Chukwuemeka Nnamdi',
    duesType: 'SERVICE_CHARGE',
    amount: 15000,
    dueDate: '2025-01-31',
    status: 'PAID',
    paidAmount: 15000,
    paidDate: '2025-01-03',
    receiptNumber: 'RCP-2025-0015',
    period: 'January 2025',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-03T10:00:00Z',
  },
  {
    id: 'dues_004',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_004',
    constituentName: 'Fatima Ibrahim',
    duesType: 'SERVICE_CHARGE',
    amount: 15000,
    dueDate: '2024-12-31',
    status: 'OVERDUE',
    paidAmount: 0,
    period: 'December 2024',
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'dues_005',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_005',
    constituentName: 'Oluwaseun Adeleke',
    duesType: 'SERVICE_CHARGE',
    amount: 20000,
    dueDate: '2024-12-31',
    status: 'OVERDUE',
    paidAmount: 0,
    period: 'December 2024',
    notes: 'Commercial property rate',
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'dues_006',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_001',
    constituentName: 'Adebayo Okonkwo',
    duesType: 'SECURITY_LEVY',
    amount: 5000,
    dueDate: '2025-01-31',
    status: 'PAID',
    paidAmount: 5000,
    paidDate: '2025-01-01',
    receiptNumber: 'RCP-2025-0002',
    period: 'January 2025',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'dues_007',
    tenantId: DEMO_TENANT_ID,
    constituentId: 'const_006',
    constituentName: 'Amara Obi',
    duesType: 'SERVICE_CHARGE',
    amount: 15000,
    dueDate: '2025-01-31',
    status: 'PAID',
    paidAmount: 15000,
    paidDate: '2025-01-02',
    receiptNumber: 'RCP-2025-0010',
    period: 'January 2025',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-02T10:00:00Z',
  },
];

// ============================================================================
// DEMO SERVICE REQUESTS
// ============================================================================

export const DEMO_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'req_001',
    tenantId: DEMO_TENANT_ID,
    ticketNumber: 'TKT-2025-10001',
    constituentId: 'const_002',
    constituentName: 'Ngozi Eze',
    category: 'INFRASTRUCTURE',
    subcategory: 'Street Light',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    subject: 'Street light not working at Block 3 junction',
    description: 'The street light at the junction of Block 3 has not been working for about 2 weeks now. This is a security concern.',
    location: 'Block 3 Junction',
    assignedTo: 'staff_001',
    assignedToName: 'Maintenance Team',
    slaHours: 72,
    slaDue: '2025-01-08T10:00:00Z',
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-01-05T14:00:00Z',
  },
  {
    id: 'req_002',
    tenantId: DEMO_TENANT_ID,
    ticketNumber: 'TKT-2025-10002',
    constituentId: 'const_001',
    constituentName: 'Adebayo Okonkwo',
    category: 'SANITATION',
    subcategory: 'Waste Collection',
    priority: 'HIGH',
    status: 'SUBMITTED',
    subject: 'Missed waste collection on Tuesday',
    description: 'The waste collection truck did not come to Block 5 area on Tuesday as scheduled. Waste is piling up.',
    location: 'Block 5 Area',
    slaHours: 24,
    slaDue: '2025-01-06T10:00:00Z',
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-01-05T10:00:00Z',
  },
  {
    id: 'req_003',
    tenantId: DEMO_TENANT_ID,
    ticketNumber: 'TKT-2025-10003',
    constituentId: 'const_003',
    constituentName: 'Chukwuemeka Nnamdi',
    category: 'SECURITY',
    subcategory: 'Gate Access',
    priority: 'LOW',
    status: 'RESOLVED',
    subject: 'Request for additional access cards',
    description: 'I need 2 additional access cards for my household members.',
    assignedTo: 'staff_002',
    assignedToName: 'Admin Office',
    slaHours: 168,
    slaDue: '2025-01-10T10:00:00Z',
    resolvedAt: '2025-01-04T15:00:00Z',
    resolutionNotes: 'Access cards issued. Card numbers: AC-2025-0045, AC-2025-0046',
    createdAt: '2025-01-03T10:00:00Z',
    updatedAt: '2025-01-04T15:00:00Z',
  },
  {
    id: 'req_004',
    tenantId: DEMO_TENANT_ID,
    ticketNumber: 'TKT-2025-10004',
    constituentId: 'const_006',
    constituentName: 'Amara Obi',
    category: 'CERTIFICATE',
    subcategory: 'Good Standing',
    priority: 'MEDIUM',
    status: 'UNDER_REVIEW',
    subject: 'Certificate of Good Standing for Employment',
    description: 'I need a certificate of good standing for my new employment. Please process urgently.',
    assignedTo: 'staff_003',
    assignedToName: 'Secretary',
    slaHours: 72,
    slaDue: '2025-01-08T10:00:00Z',
    createdAt: '2025-01-05T09:00:00Z',
    updatedAt: '2025-01-05T11:00:00Z',
  },
  {
    id: 'req_005',
    tenantId: DEMO_TENANT_ID,
    ticketNumber: 'TKT-2024-09876',
    constituentId: 'const_004',
    constituentName: 'Fatima Ibrahim',
    category: 'COMPLAINT',
    subcategory: 'Noise',
    priority: 'MEDIUM',
    status: 'CLOSED',
    subject: 'Noise complaint - Construction work at odd hours',
    description: 'Construction work at Plot 6 Block 2 continues past 6pm which is against estate rules.',
    location: 'Plot 6, Block 2',
    assignedTo: 'staff_001',
    assignedToName: 'Estate Manager',
    slaHours: 72,
    slaDue: '2024-12-20T10:00:00Z',
    resolvedAt: '2024-12-19T16:00:00Z',
    resolutionNotes: 'Warning issued to the contractor. Issue resolved.',
    createdAt: '2024-12-17T10:00:00Z',
    updatedAt: '2024-12-19T16:00:00Z',
  },
];

// ============================================================================
// DEMO CERTIFICATES
// ============================================================================

export const DEMO_CERTIFICATES: Certificate[] = [
  {
    id: 'cert_001',
    tenantId: DEMO_TENANT_ID,
    certificateNumber: 'GOO-2025-0001',
    constituentId: 'const_001',
    constituentName: 'Adebayo Okonkwo',
    certificateType: 'GOOD_STANDING',
    purpose: 'Bank Loan Application',
    status: 'ISSUED',
    issuedDate: '2025-01-02',
    validUntil: '2025-07-02',
    issuedBy: 'Estate Secretary',
    verificationCode: 'GS-ABC123XYZ',
    feePaid: 2500,
    invoiceId: 'inv_cert_001',
    createdAt: '2025-01-02T10:00:00Z',
    updatedAt: '2025-01-02T10:00:00Z',
  },
  {
    id: 'cert_002',
    tenantId: DEMO_TENANT_ID,
    certificateNumber: 'RES-2024-0089',
    constituentId: 'const_003',
    constituentName: 'Chukwuemeka Nnamdi',
    certificateType: 'RESIDENCY',
    purpose: 'School Registration',
    status: 'ISSUED',
    issuedDate: '2024-09-15',
    validUntil: '2025-09-15',
    issuedBy: 'Estate Secretary',
    verificationCode: 'RS-DEF456UVW',
    feePaid: 3000,
    invoiceId: 'inv_cert_002',
    createdAt: '2024-09-15T10:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
  },
  {
    id: 'cert_003',
    tenantId: DEMO_TENANT_ID,
    certificateNumber: 'GOO-2025-0002',
    constituentId: 'const_006',
    constituentName: 'Amara Obi',
    certificateType: 'GOOD_STANDING',
    purpose: 'Employment Verification',
    status: 'PENDING',
    verificationCode: 'GS-GHI789RST',
    feePaid: 2500,
    invoiceId: 'inv_cert_003',
    createdAt: '2025-01-05T09:00:00Z',
    updatedAt: '2025-01-05T09:00:00Z',
  },
  {
    id: 'cert_004',
    tenantId: DEMO_TENANT_ID,
    certificateNumber: 'INT-2024-0156',
    constituentId: 'const_002',
    constituentName: 'Ngozi Eze',
    certificateType: 'INTRODUCTION_LETTER',
    purpose: 'Bank Account Opening',
    status: 'ISSUED',
    issuedDate: '2024-11-20',
    validUntil: '2024-12-20',
    issuedBy: 'Estate Secretary',
    verificationCode: 'IL-JKL012MNO',
    feePaid: 1000,
    invoiceId: 'inv_cert_004',
    createdAt: '2024-11-20T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
  },
];

// ============================================================================
// DEMO EVENTS
// ============================================================================

export const DEMO_EVENTS: CivicEvent[] = [
  {
    id: 'evt_001',
    tenantId: DEMO_TENANT_ID,
    eventType: 'AGM',
    title: '2025 Annual General Meeting',
    description: 'Annual general meeting of all Harmony Estate residents. Agenda includes financial report, election of new executives, and development plans.',
    venue: 'Harmony Estate Community Hall',
    eventDate: '2025-02-15',
    startTime: '10:00',
    endTime: '14:00',
    status: 'SCHEDULED',
    expectedAttendees: 200,
    actualAttendees: 0,
    quorumRequired: 100,
    quorumMet: false,
    agenda: [
      'Opening Prayer',
      'Chairman\'s Address',
      'Secretary\'s Report',
      'Financial Report',
      'Election of New Executives',
      'Development Plans for 2025',
      'Any Other Business',
      'Closing',
    ],
    createdBy: 'admin',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'evt_002',
    tenantId: DEMO_TENANT_ID,
    eventType: 'EXECUTIVE',
    title: 'January Executive Committee Meeting',
    description: 'Monthly executive committee meeting to review estate operations and plan activities.',
    venue: 'Estate Office, Conference Room',
    eventDate: '2025-01-20',
    startTime: '16:00',
    endTime: '18:00',
    status: 'SCHEDULED',
    expectedAttendees: 12,
    actualAttendees: 0,
    quorumRequired: 7,
    quorumMet: false,
    agenda: [
      'Review of December 2024 Activities',
      'Financial Update',
      'Security Report',
      'AGM Preparation',
      'Any Other Business',
    ],
    createdBy: 'admin',
    createdAt: '2025-01-02T10:00:00Z',
    updatedAt: '2025-01-02T10:00:00Z',
  },
  {
    id: 'evt_003',
    tenantId: DEMO_TENANT_ID,
    eventType: 'SANITATION',
    title: 'January Community Sanitation Day',
    description: 'Monthly community sanitation exercise. All residents are expected to participate in cleaning their surroundings.',
    venue: 'Entire Estate',
    eventDate: '2025-01-25',
    startTime: '07:00',
    endTime: '10:00',
    status: 'SCHEDULED',
    expectedAttendees: 300,
    actualAttendees: 0,
    quorumRequired: 0,
    quorumMet: true,
    createdBy: 'admin',
    createdAt: '2025-01-03T10:00:00Z',
    updatedAt: '2025-01-03T10:00:00Z',
  },
  {
    id: 'evt_004',
    tenantId: DEMO_TENANT_ID,
    eventType: 'COMMUNITY',
    title: 'End of Year Party 2024',
    description: 'Annual end of year celebration for all estate residents.',
    venue: 'Harmony Estate Community Hall',
    eventDate: '2024-12-21',
    startTime: '16:00',
    endTime: '22:00',
    status: 'COMPLETED',
    expectedAttendees: 250,
    actualAttendees: 185,
    quorumRequired: 0,
    quorumMet: true,
    createdBy: 'admin',
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2024-12-22T10:00:00Z',
  },
];

// ============================================================================
// DEMO POLLS
// ============================================================================

export const DEMO_POLLS: Poll[] = [
  {
    id: 'poll_001',
    tenantId: DEMO_TENANT_ID,
    pollType: 'ELECTION',
    title: 'Executive Committee Election 2025',
    description: 'Election of new executive committee members for the 2025-2027 tenure.',
    positions: [
      {
        key: 'CHAIRMAN',
        title: 'Chairman',
        candidates: [
          { id: 'cand_001', name: 'Chief Adebayo Okonkwo', manifesto: 'Building a safer and more developed community' },
          { id: 'cand_002', name: 'Dr. Emeka Okafor', manifesto: 'Transparency and accountability in governance' },
        ],
      },
      {
        key: 'SECRETARY',
        title: 'General Secretary',
        candidates: [
          { id: 'cand_003', name: 'Mrs. Ngozi Eze', manifesto: 'Efficient communication and record keeping' },
          { id: 'cand_004', name: 'Mr. Ahmed Bello', manifesto: 'Digital transformation of estate administration' },
        ],
      },
      {
        key: 'TREASURER',
        title: 'Treasurer',
        candidates: [
          { id: 'cand_005', name: 'Alhaji Ibrahim Musa', manifesto: 'Prudent financial management' },
          { id: 'cand_006', name: 'Mrs. Amara Obi', manifesto: 'Transparent budgeting and reporting' },
        ],
      },
    ],
    votingStart: '2025-02-15T12:00:00Z',
    votingEnd: '2025-02-15T15:00:00Z',
    eligibleVotersCount: 180,
    status: 'SCHEDULED',
    totalVotes: 0,
    createdBy: 'admin',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'poll_002',
    tenantId: DEMO_TENANT_ID,
    pollType: 'DECISION',
    title: 'Proposal: Install CCTV Cameras at All Entry Points',
    description: 'Vote on the proposal to install additional CCTV cameras at all estate entry and exit points. Estimated cost: ₦5,000,000.',
    options: [
      { key: 'YES', label: 'Yes, I support the proposal' },
      { key: 'NO', label: 'No, I do not support the proposal' },
      { key: 'ABSTAIN', label: 'Abstain' },
    ],
    votingStart: '2025-02-15T15:30:00Z',
    votingEnd: '2025-02-15T16:00:00Z',
    eligibleVotersCount: 180,
    status: 'SCHEDULED',
    totalVotes: 0,
    createdBy: 'admin',
    createdAt: '2025-01-02T10:00:00Z',
    updatedAt: '2025-01-02T10:00:00Z',
  },
  {
    id: 'poll_003',
    tenantId: DEMO_TENANT_ID,
    pollType: 'BUDGET_APPROVAL',
    title: '2025 Annual Budget Approval',
    description: 'Vote to approve the proposed 2025 annual budget of ₦45,000,000.',
    options: [
      { key: 'APPROVE', label: 'Approve the budget as presented' },
      { key: 'REJECT', label: 'Reject the budget - requires revision' },
      { key: 'ABSTAIN', label: 'Abstain' },
    ],
    votingStart: '2025-02-15T16:00:00Z',
    votingEnd: '2025-02-15T16:30:00Z',
    eligibleVotersCount: 180,
    status: 'SCHEDULED',
    totalVotes: 0,
    createdBy: 'admin',
    createdAt: '2025-01-03T10:00:00Z',
    updatedAt: '2025-01-03T10:00:00Z',
  },
];

// ============================================================================
// DEMO STATS SUMMARY
// ============================================================================

export const DEMO_STATS = {
  totalConstituents: DEMO_CONSTITUENTS.length,
  activeConstituents: DEMO_CONSTITUENTS.filter((c: any) => c.membershipStatus === 'ACTIVE').length,
  totalDuesCollected: 50000,
  pendingDues: 30000,
  overdueDues: 55000,
  openServiceRequests: DEMO_SERVICE_REQUESTS.filter((r: any) => !['RESOLVED', 'CLOSED', 'REJECTED'].includes(r.status)).length,
  resolvedThisMonth: DEMO_SERVICE_REQUESTS.filter((r: any) => r.status === 'RESOLVED').length,
  certificatesIssued: DEMO_CERTIFICATES.filter((c: any) => c.status === 'ISSUED').length,
  upcomingEvents: DEMO_EVENTS.filter((e: any) => e.status === 'SCHEDULED').length,
  scheduledPolls: DEMO_POLLS.filter((p: any) => p.status === 'SCHEDULED').length,
};

// ============================================================================
// IN-MEMORY STORAGE (For demo operations)
// ============================================================================

// These will be populated with demo data on first access
let constituentsStore: Constituent[] = [...DEMO_CONSTITUENTS];
let duesStore: DuesRecord[] = [...DEMO_DUES];
let serviceRequestsStore: ServiceRequest[] = [...DEMO_SERVICE_REQUESTS];
let certificatesStore: Certificate[] = [...DEMO_CERTIFICATES];
let eventsStore: CivicEvent[] = [...DEMO_EVENTS];
let pollsStore: Poll[] = [...DEMO_POLLS];
let votesStore: Vote[] = [];

export function getConstituentsStore() { return constituentsStore; }
export function getDuesStore() { return duesStore; }
export function getServiceRequestsStore() { return serviceRequestsStore; }
export function getCertificatesStore() { return certificatesStore; }
export function getEventsStore() { return eventsStore; }
export function getPollsStore() { return pollsStore; }
export function getVotesStore() { return votesStore; }

export function resetDemoData() {
  constituentsStore = [...DEMO_CONSTITUENTS];
  duesStore = [...DEMO_DUES];
  serviceRequestsStore = [...DEMO_SERVICE_REQUESTS];
  certificatesStore = [...DEMO_CERTIFICATES];
  eventsStore = [...DEMO_EVENTS];
  pollsStore = [...DEMO_POLLS];
  votesStore = [];
}
