import {
  Store, GraduationCap, Heart, Landmark, Hotel, Truck,
  ShoppingCart, Package, Users, Briefcase, Building, Church,
  Vote, Home, Wrench, Scale, UserPlus, Warehouse, FileText,
  Globe, LayoutDashboard, LucideIcon
} from 'lucide-react'

export interface Suite {
  id: string
  name: string
  shortName: string
  tagline: string
  description: string
  icon: LucideIcon
  category: 'commerce' | 'service' | 'community' | 'operations'
  demoStrength: 'strong' | 'medium' | 'mention'
  capabilities: string[]
  bestFor: string[]
  demoTenant?: {
    name: string
    slug: string
    stats: string
  }
}

export const suites: Suite[] = [
  {
    id: 'pos',
    name: 'WebWaka POS',
    shortName: 'POS',
    tagline: 'Retail and Point-of-Sale Management',
    description: 'Everything a retail business needs to sell, track inventory, and manage customers. Works on any device, online or offline.',
    icon: ShoppingCart,
    category: 'commerce',
    demoStrength: 'strong',
    capabilities: ['Sales transactions with receipt printing', 'Inventory tracking with low-stock alerts', 'Customer records and purchase history', 'Shift management and cash reconciliation', 'Daily sales reports'],
    bestFor: ['Supermarkets', 'Pharmacies', 'Electronics shops', 'Boutiques', 'Restaurant counters'],
    demoTenant: { name: 'Lagos Retail Store', slug: 'demo-retail-store', stats: '25 products, 20+ sales, 2 shifts' },
  },
  {
    id: 'storefront',
    name: 'WebWaka Storefront',
    shortName: 'Storefront',
    tagline: 'E-commerce and Online Sales',
    description: 'A complete online store with product catalogs, order management, and delivery coordination. Sell online without building a website.',
    icon: Store,
    category: 'commerce',
    demoStrength: 'strong',
    capabilities: ['Product catalog with categories and variants', 'Shopping cart and checkout', 'Order tracking and fulfillment', 'Delivery integration', 'Customer notifications'],
    bestFor: ['Fashion brands', 'Food vendors', 'Wholesale distributors', 'Artisans'],
  },
  {
    id: 'marketplace',
    name: 'WebWaka Marketplace',
    shortName: 'Marketplace',
    tagline: 'Multi-Vendor Platform',
    description: 'Run a marketplace where multiple vendors sell through one platform. You manage the platform, vendors manage their products.',
    icon: Package,
    category: 'commerce',
    demoStrength: 'strong',
    capabilities: ['Vendor onboarding and management', 'Commission and fee structures', 'Centralized order processing', 'Vendor payout tracking', 'Platform analytics'],
    bestFor: ['Mall operators', 'Trade associations', 'Cooperative societies', 'Market aggregators'],
    demoTenant: { name: 'Naija Market Hub', slug: 'demo-marketplace', stats: 'Multi-vendor demo with complete workflow' },
  },
  {
    id: 'hospitality',
    name: 'WebWaka Hospitality',
    shortName: 'Hospitality',
    tagline: 'Hotels, Restaurants, and Events',
    description: 'Manage rooms, tables, and event spaces with integrated reservations, billing, and guest services.',
    icon: Hotel,
    category: 'commerce',
    demoStrength: 'strong',
    capabilities: ['Room and table reservations', 'Guest check-in and check-out', 'Housekeeping management', 'Restaurant order taking', 'Event booking and catering', 'Folio and billing'],
    bestFor: ['Hotels', 'Guest houses', 'Restaurants', 'Event centers', 'Catering companies'],
    demoTenant: { name: 'PalmView Suites Lagos', slug: 'demo-hotel', stats: '10+ reservations, complete hotel workflow' },
  },
  {
    id: 'logistics',
    name: 'WebWaka Logistics',
    shortName: 'Logistics',
    tagline: 'Delivery and Fleet Management',
    description: 'Track shipments, manage drivers, optimize routes, and coordinate deliveries from pickup to proof of delivery.',
    icon: Truck,
    category: 'commerce',
    demoStrength: 'medium',
    capabilities: ['Shipment creation and tracking', 'Driver assignment and management', 'Route optimization', 'Proof of delivery capture', 'Fleet maintenance scheduling'],
    bestFor: ['Delivery companies', 'Courier services', 'Distribution businesses', 'Moving companies'],
    demoTenant: { name: 'Swift Logistics', slug: 'demo-logistics', stats: '15+ shipments, driver assignment' },
  },
  {
    id: 'education',
    name: 'WebWaka Education',
    shortName: 'Education',
    tagline: 'Schools and Training Centers',
    description: 'Complete school management from enrollment to graduation. Track students, manage classes, collect fees, and communicate with parents.',
    icon: GraduationCap,
    category: 'service',
    demoStrength: 'strong',
    capabilities: ['Student enrollment and records', 'Class and subject management', 'Attendance tracking (525+ demo records)', 'Grade entry and report cards (226+ results)', 'Fee collection and receipts', 'Parent communication'],
    bestFor: ['Primary schools', 'Secondary schools', 'Training centers', 'Tutorial centers', 'Crèches'],
    demoTenant: { name: 'Bright Future Academy', slug: 'demo-school', stats: '121 students, 525 attendance, 226 results' },
  },
  {
    id: 'health',
    name: 'WebWaka Health',
    shortName: 'Health',
    tagline: 'Clinics and Healthcare Providers',
    description: 'Patient management, appointments, prescriptions, and lab orders. Built for Nigerian healthcare providers.',
    icon: Heart,
    category: 'service',
    demoStrength: 'strong',
    capabilities: ['Patient registration and records', 'Appointment scheduling', 'Clinical encounters and notes', 'Prescription management (15+ demo records)', 'Lab order tracking', 'Billing and receipts'],
    bestFor: ['Clinics', 'Pharmacies', 'Diagnostic centers', 'Specialist practices', 'Health centers'],
    demoTenant: { name: 'HealthFirst Clinic', slug: 'demo-clinic', stats: '37 patients, 12 encounters, 15 prescriptions' },
  },
  {
    id: 'legal',
    name: 'WebWaka Legal',
    shortName: 'Legal',
    tagline: 'Law Firms and Chambers',
    description: 'Manage matters, track billable time, handle deadlines, and coordinate documents for legal practice.',
    icon: Scale,
    category: 'service',
    demoStrength: 'medium',
    capabilities: ['Matter management', 'Time entry and billing', 'Deadline tracking', 'Document management', 'Client portal', 'Trust accounting'],
    bestFor: ['Law firms', 'Chambers', 'Legal consultants', 'In-house legal departments'],
  },
  {
    id: 'recruitment',
    name: 'WebWaka Recruitment',
    shortName: 'Recruitment',
    tagline: 'Hiring and Onboarding',
    description: 'Manage job postings, track applications, schedule interviews, and onboard new hires.',
    icon: UserPlus,
    category: 'service',
    demoStrength: 'medium',
    capabilities: ['Job posting and distribution', 'Application tracking', 'Interview scheduling', 'Candidate scoring', 'Offer management', 'Onboarding checklists'],
    bestFor: ['HR departments', 'Recruitment agencies', 'Staffing companies'],
  },
  {
    id: 'real-estate',
    name: 'WebWaka Real Estate',
    shortName: 'Real Estate',
    tagline: 'Property Management',
    description: 'Manage properties, track leases, collect rent, and handle maintenance requests.',
    icon: Home,
    category: 'service',
    demoStrength: 'strong',
    capabilities: ['Property and unit management', 'Tenant onboarding', 'Lease tracking', 'Rent collection and reminders', 'Maintenance request handling', 'Payment history'],
    bestFor: ['Property managers', 'Landlords', 'Estate agents', 'Housing cooperatives'],
    demoTenant: { name: 'Lagos Property Managers', slug: 'demo-real-estate', stats: 'Properties, leases, 8+ rent payments' },
  },
  {
    id: 'church',
    name: 'WebWaka Church',
    shortName: 'Church',
    tagline: 'Faith Organizations',
    description: 'Manage members, track giving, coordinate ministries, and build community. Built for Nigerian churches and faith organizations.',
    icon: Church,
    category: 'community',
    demoStrength: 'strong',
    capabilities: ['Member registration and profiles', 'Giving and donation tracking (37+ demo records)', 'Attendance for services (57+ demo records)', 'Cell/small group management', 'Ministry and department coordination', 'Event management'],
    bestFor: ['Churches', 'Mosques', 'Religious organizations', 'Faith-based NGOs'],
    demoTenant: { name: 'GraceLife Community Church', slug: 'demo-church', stats: '45+ members with giving and attendance' },
  },
  {
    id: 'political',
    name: 'WebWaka Political',
    shortName: 'Political',
    tagline: 'Campaigns and Party Operations',
    description: 'Manage campaign volunteers, track donations, coordinate events, and organize constituency outreach.',
    icon: Vote,
    category: 'community',
    demoStrength: 'strong',
    capabilities: ['Member and supporter registration', 'Volunteer management (25+ demo records)', 'Donation tracking', 'Event coordination', 'Constituency mapping', 'Campaign reporting'],
    bestFor: ['Political parties', 'Campaign organizations', 'Advocacy groups', 'Constituency offices'],
    demoTenant: { name: 'Lagos Campaign HQ', slug: 'demo-political', stats: '35+ members with volunteer and donation' },
  },
  {
    id: 'civic',
    name: 'WebWaka Civic',
    shortName: 'Civic',
    tagline: 'Associations and Community Organizations',
    description: 'Manage members, collect dues, run elections, and coordinate community projects.',
    icon: Landmark,
    category: 'community',
    demoStrength: 'medium',
    capabilities: ['Member registration', 'Dues collection and tracking', 'Voting and elections', 'Project management', 'Service request handling', 'Community announcements'],
    bestFor: ['Resident associations', 'Professional bodies', 'Trade groups', 'Alumni associations', 'Cooperative societies'],
    demoTenant: { name: 'Lagos State Lands Bureau', slug: 'demo-civic', stats: '12+ cases, dues collection' },
  },
  {
    id: 'projects',
    name: 'WebWaka Projects',
    shortName: 'Projects',
    tagline: 'Project Management',
    description: 'Track projects, manage tasks, monitor budgets, and coordinate team members.',
    icon: LayoutDashboard,
    category: 'operations',
    demoStrength: 'medium',
    capabilities: ['Project creation and tracking', 'Task assignment and status', 'Milestone management', 'Budget tracking', 'Team coordination', 'Project reporting'],
    bestFor: ['Project teams', 'Agencies', 'Construction companies', 'IT departments'],
  },
  {
    id: 'hr',
    name: 'WebWaka HR',
    shortName: 'HR',
    tagline: 'Human Resources',
    description: 'Manage employees, track attendance, process payroll, and handle leave requests.',
    icon: Users,
    category: 'operations',
    demoStrength: 'medium',
    capabilities: ['Employee records', 'Attendance tracking', 'Leave management', 'Payroll processing', 'Payslip generation', 'Department management'],
    bestFor: ['Any business with employees', 'HR departments', 'Payroll processors'],
  },
  {
    id: 'warehouse',
    name: 'WebWaka Warehouse',
    shortName: 'Warehouse',
    tagline: 'Advanced Warehouse Management',
    description: 'Manage warehouse operations with location tracking, picking optimization, and inventory accuracy.',
    icon: Warehouse,
    category: 'operations',
    demoStrength: 'medium',
    capabilities: ['Location and bin management', 'Receiving and put-away', 'Picking and packing', 'Inventory counting', 'Stock movements', 'Warehouse reporting'],
    bestFor: ['Fulfillment centers', 'Distribution warehouses', '3PL providers'],
  },
  {
    id: 'procurement',
    name: 'WebWaka Procurement',
    shortName: 'Procurement',
    tagline: 'Purchase Management',
    description: 'Manage purchase requests, vendor relationships, and goods receipt across the organization.',
    icon: FileText,
    category: 'operations',
    demoStrength: 'mention',
    capabilities: ['Purchase request creation', 'Approval workflows', 'Vendor management', 'Purchase order generation', 'Goods receipt', 'Spend tracking'],
    bestFor: ['Any business with purchasing needs', 'Procurement departments'],
  },
  {
    id: 'sites-funnels',
    name: 'WebWaka Sites & Funnels',
    shortName: 'Sites & Funnels',
    tagline: 'Website and Funnel Builder for Partners',
    description: 'Build professional websites and conversion funnels for your clients. Industry-specific templates, AI content generation, and seamless integration with all WebWaka suites.',
    icon: Globe,
    category: 'operations',
    demoStrength: 'strong',
    capabilities: ['Drag-and-drop site builder', 'Industry-specific templates', 'Conversion funnel creation', 'AI-powered content generation', 'Custom domain support', 'Analytics and lead capture'],
    bestFor: ['Digital agencies', 'Marketing consultants', 'All WebWaka partners'],
  },
]

export const suitesByCategory = {
  commerce: suites.filter(s => s.category === 'commerce'),
  service: suites.filter(s => s.category === 'service'),
  community: suites.filter(s => s.category === 'community'),
  operations: suites.filter(s => s.category === 'operations'),
}

export const categoryLabels = {
  commerce: 'Commerce Suites',
  service: 'Service Suites',
  community: 'Community Suites',
  operations: 'Operations Suites',
}

export const demoTenants = [
  { name: 'Lagos Retail Store', slug: 'demo-retail-store', industry: 'Retail', category: 'commerce' as const, stats: '25 products, 20+ sales' },
  { name: 'Naija Market Hub', slug: 'demo-marketplace', industry: 'Marketplace', category: 'commerce' as const, stats: 'Multi-vendor marketplace' },
  { name: 'PalmView Suites Lagos', slug: 'demo-hotel', industry: 'Hospitality', category: 'commerce' as const, stats: '10+ reservations' },
  { name: 'Swift Logistics', slug: 'demo-logistics', industry: 'Logistics', category: 'commerce' as const, stats: '15+ shipments' },
  { name: 'Bright Future Academy', slug: 'demo-school', industry: 'Education', category: 'service' as const, stats: '121 students, 525 attendance' },
  { name: 'HealthFirst Clinic', slug: 'demo-clinic', industry: 'Healthcare', category: 'service' as const, stats: '37 patients, 12 encounters' },
  { name: 'Lagos Property Managers', slug: 'demo-real-estate', industry: 'Real Estate', category: 'service' as const, stats: 'Properties, 8+ rent payments' },
  { name: 'GraceLife Community Church', slug: 'demo-church', industry: 'Church', category: 'community' as const, stats: '45+ members, 37 donations' },
  { name: 'Lagos Campaign HQ', slug: 'demo-political', industry: 'Political', category: 'community' as const, stats: '35+ members, 25 volunteers' },
  { name: 'Lagos State Lands Bureau', slug: 'demo-civic', industry: 'Civic', category: 'community' as const, stats: '12+ cases' },
]
