/**
 * LOGISTICS SUITE: Demo Data
 * 
 * In-memory demo data for the Logistics Suite.
 * Represents "Swift Dispatch Co." - a Lagos-based logistics company.
 * 
 * ⚠️ DEMO ONLY - Data resets on page refresh
 */

import {
  Vehicle,
  Driver,
  Job,
  ProofOfDelivery,
  VehicleType,
  VehicleStatus,
  DriverStatus,
  JobStatus,
  JobType,
  JobPriority,
  BillingType,
  PaymentMethod,
  LicenseType,
} from './config';

// ============================================================================
// DEMO TENANT
// ============================================================================

export const DEMO_TENANT_ID = 'demo-logistics';
export const DEMO_COMPANY_NAME = 'Swift Dispatch Co.';
export const DEMO_COMPANY_LOCATION = 'Lagos, Nigeria';

// ============================================================================
// IN-MEMORY STORES
// ============================================================================

let vehiclesStore: Vehicle[] = [];
let driversStore: Driver[] = [];
let jobsStore: Job[] = [];
let podStore: ProofOfDelivery[] = [];

// ============================================================================
// DEMO VEHICLES (10)
// ============================================================================

export const DEMO_VEHICLES: Vehicle[] = [
  // Motorcycles (3)
  {
    id: 'veh_001',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-123-AB',
    vehicleType: 'MOTORCYCLE',
    make: 'Bajaj',
    model: 'Boxer 150',
    year: 2023,
    color: 'Red',
    status: 'AVAILABLE',
    capacity: 50,
    fuelType: 'PETROL',
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'veh_002',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-456-CD',
    vehicleType: 'MOTORCYCLE',
    make: 'TVS',
    model: 'Apache 160',
    year: 2023,
    color: 'Black',
    status: 'IN_USE',
    capacity: 50,
    currentDriverId: 'drv_001',
    currentDriverName: 'Chukwuemeka Obi',
    fuelType: 'PETROL',
    isActive: true,
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'veh_003',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-789-EF',
    vehicleType: 'MOTORCYCLE',
    make: 'Honda',
    model: 'ACE 125',
    year: 2022,
    color: 'Blue',
    status: 'MAINTENANCE',
    capacity: 50,
    fuelType: 'PETROL',
    lastServiceDate: '2024-05-15',
    isActive: true,
    createdAt: '2023-06-20T08:00:00Z',
    updatedAt: '2024-06-01T08:00:00Z',
  },
  // Tricycles (2)
  {
    id: 'veh_004',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-111-GH',
    vehicleType: 'TRICYCLE',
    make: 'Piaggio',
    model: 'Ape City',
    year: 2023,
    color: 'Yellow',
    status: 'AVAILABLE',
    capacity: 200,
    fuelType: 'PETROL',
    isActive: true,
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'veh_005',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-222-IJ',
    vehicleType: 'TRICYCLE',
    make: 'TVS',
    model: 'King Deluxe',
    year: 2022,
    color: 'Green',
    status: 'IN_USE',
    capacity: 200,
    currentDriverId: 'drv_003',
    currentDriverName: 'Adebayo Ogundimu',
    fuelType: 'PETROL',
    isActive: true,
    createdAt: '2023-08-10T08:00:00Z',
    updatedAt: '2024-06-01T11:00:00Z',
  },
  // Vans (2)
  {
    id: 'veh_006',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-333-KL',
    vehicleType: 'VAN',
    make: 'Toyota',
    model: 'Hiace',
    year: 2021,
    color: 'White',
    status: 'AVAILABLE',
    capacity: 1000,
    fuelType: 'DIESEL',
    insuranceExpiry: '2025-03-15',
    isActive: true,
    createdAt: '2022-11-05T08:00:00Z',
    updatedAt: '2024-05-20T08:00:00Z',
  },
  {
    id: 'veh_007',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-444-MN',
    vehicleType: 'VAN',
    make: 'Ford',
    model: 'Transit',
    year: 2022,
    color: 'Silver',
    status: 'IN_USE',
    capacity: 1200,
    currentDriverId: 'drv_004',
    currentDriverName: 'Ibrahim Musa',
    fuelType: 'DIESEL',
    insuranceExpiry: '2025-06-20',
    isActive: true,
    createdAt: '2023-03-15T08:00:00Z',
    updatedAt: '2024-06-01T09:00:00Z',
  },
  // Trucks (2)
  {
    id: 'veh_008',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-555-OP',
    vehicleType: 'TRUCK_SMALL',
    make: 'Isuzu',
    model: 'NKR',
    year: 2020,
    color: 'Blue',
    status: 'AVAILABLE',
    capacity: 3000,
    fuelType: 'DIESEL',
    insuranceExpiry: '2025-01-10',
    isActive: true,
    createdAt: '2021-07-20T08:00:00Z',
    updatedAt: '2024-04-15T08:00:00Z',
  },
  {
    id: 'veh_009',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-666-QR',
    vehicleType: 'TRUCK_MEDIUM',
    make: 'MAN',
    model: 'TGM 18.290',
    year: 2019,
    color: 'Red',
    status: 'RESERVED',
    capacity: 8000,
    fuelType: 'DIESEL',
    insuranceExpiry: '2024-12-31',
    isActive: true,
    createdAt: '2020-09-10T08:00:00Z',
    updatedAt: '2024-06-01T07:00:00Z',
  },
  // Out of service
  {
    id: 'veh_010',
    tenantId: DEMO_TENANT_ID,
    vehicleNumber: 'LAG-777-ST',
    vehicleType: 'PICKUP',
    make: 'Toyota',
    model: 'Hilux',
    year: 2018,
    color: 'Black',
    status: 'OUT_OF_SERVICE',
    capacity: 800,
    fuelType: 'DIESEL',
    isActive: false,
    createdAt: '2019-04-22T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z',
  },
];

// ============================================================================
// DEMO DRIVERS (6)
// ============================================================================

export const DEMO_DRIVERS: Driver[] = [
  {
    id: 'drv_001',
    tenantId: DEMO_TENANT_ID,
    driverNumber: 'DRV-10001',
    firstName: 'Chukwuemeka',
    lastName: 'Obi',
    phone: '08012345678',
    email: 'chukwuemeka@swiftdispatch.ng',
    licenseNumber: 'SMK28374659',
    licenseType: 'CLASS_A',
    licenseExpiry: '2026-08-15',
    ninNumber: '12345678901',
    status: 'ON_TRIP',
    currentVehicleId: 'veh_002',
    currentVehicleNumber: 'LAG-456-CD',
    currentJobId: 'job_002',
    rating: 4.8,
    totalTrips: 342,
    totalEarnings: 1250000,
    bankName: 'GTBank',
    bankAccount: '0123456789',
    emergencyContact: 'Mrs. Obi',
    emergencyPhone: '08098765432',
    isActive: true,
    joinedAt: '2023-01-15',
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'drv_002',
    tenantId: DEMO_TENANT_ID,
    driverNumber: 'DRV-10002',
    firstName: 'Ngozi',
    lastName: 'Eze',
    phone: '08023456789',
    email: 'ngozi@swiftdispatch.ng',
    licenseNumber: 'SMK38475610',
    licenseType: 'CLASS_A',
    licenseExpiry: '2025-12-20',
    status: 'AVAILABLE',
    rating: 4.9,
    totalTrips: 287,
    totalEarnings: 980000,
    bankName: 'Access Bank',
    bankAccount: '0234567890',
    isActive: true,
    joinedAt: '2023-03-10',
    createdAt: '2023-03-10T08:00:00Z',
    updatedAt: '2024-05-28T14:00:00Z',
  },
  {
    id: 'drv_003',
    tenantId: DEMO_TENANT_ID,
    driverNumber: 'DRV-10003',
    firstName: 'Adebayo',
    lastName: 'Ogundimu',
    phone: '08034567890',
    email: 'adebayo@swiftdispatch.ng',
    licenseNumber: 'LAG48576721',
    licenseType: 'CLASS_B',
    licenseExpiry: '2026-03-05',
    ninNumber: '23456789012',
    status: 'ON_TRIP',
    currentVehicleId: 'veh_005',
    currentVehicleNumber: 'LAG-222-IJ',
    currentJobId: 'job_003',
    rating: 4.6,
    totalTrips: 198,
    totalEarnings: 720000,
    bankName: 'First Bank',
    bankAccount: '3456789012',
    isActive: true,
    joinedAt: '2023-06-22',
    createdAt: '2023-06-22T08:00:00Z',
    updatedAt: '2024-06-01T11:00:00Z',
  },
  {
    id: 'drv_004',
    tenantId: DEMO_TENANT_ID,
    driverNumber: 'DRV-10004',
    firstName: 'Ibrahim',
    lastName: 'Musa',
    phone: '08045678901',
    email: 'ibrahim@swiftdispatch.ng',
    licenseNumber: 'KN59687832',
    licenseType: 'CLASS_C',
    licenseExpiry: '2025-09-18',
    ninNumber: '34567890123',
    status: 'ON_TRIP',
    currentVehicleId: 'veh_007',
    currentVehicleNumber: 'LAG-444-MN',
    currentJobId: 'job_004',
    rating: 4.7,
    totalTrips: 156,
    totalEarnings: 890000,
    bankName: 'UBA',
    bankAccount: '4567890123',
    emergencyContact: 'Aisha Musa',
    emergencyPhone: '08087654321',
    isActive: true,
    joinedAt: '2023-09-05',
    createdAt: '2023-09-05T08:00:00Z',
    updatedAt: '2024-06-01T09:00:00Z',
  },
  {
    id: 'drv_005',
    tenantId: DEMO_TENANT_ID,
    driverNumber: 'DRV-10005',
    firstName: 'Funke',
    lastName: 'Adeyemi',
    phone: '08056789012',
    email: 'funke@swiftdispatch.ng',
    licenseNumber: 'OY60798943',
    licenseType: 'CLASS_B',
    licenseExpiry: '2026-01-30',
    status: 'OFF_DUTY',
    rating: 4.5,
    totalTrips: 89,
    totalEarnings: 320000,
    bankName: 'Zenith Bank',
    bankAccount: '5678901234',
    isActive: true,
    joinedAt: '2024-01-08',
    createdAt: '2024-01-08T08:00:00Z',
    updatedAt: '2024-06-01T06:00:00Z',
  },
  {
    id: 'drv_006',
    tenantId: DEMO_TENANT_ID,
    driverNumber: 'DRV-10006',
    firstName: 'Uche',
    lastName: 'Nnamdi',
    phone: '08067890123',
    licenseNumber: 'EN71809054',
    licenseType: 'CLASS_D',
    licenseExpiry: '2025-07-12',
    status: 'SUSPENDED',
    rating: 3.8,
    totalTrips: 45,
    totalEarnings: 180000,
    isActive: false,
    joinedAt: '2024-02-20',
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-05-15T08:00:00Z',
  },
];

// ============================================================================
// DEMO JOBS (8)
// ============================================================================

const today = new Date().toISOString().split('T')[0];

export const DEMO_JOBS: Job[] = [
  // Completed job
  {
    id: 'job_001',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-A1B2C3-XYZ',
    jobType: 'DELIVERY',
    status: 'COMPLETED',
    priority: 'NORMAL',
    driverId: 'drv_002',
    driverName: 'Ngozi Eze',
    vehicleId: 'veh_001',
    vehicleNumber: 'LAG-123-AB',
    assignedAt: `${today}T08:00:00Z`,
    acceptedAt: `${today}T08:05:00Z`,
    pickupAddress: '15 Broad Street, Lagos Island',
    pickupLandmark: 'Near First Bank HQ',
    pickupContactName: 'Mr. Johnson',
    pickupContactPhone: '08011111111',
    scheduledPickupTime: `${today}T09:00:00Z`,
    actualPickupTime: `${today}T09:15:00Z`,
    deliveryAddress: '42 Awolowo Road, Ikoyi',
    deliveryLandmark: 'Opposite Chicken Republic',
    deliveryContactName: 'Mrs. Williams',
    deliveryContactPhone: '08022222222',
    scheduledDeliveryTime: `${today}T10:00:00Z`,
    actualDeliveryTime: `${today}T10:30:00Z`,
    itemDescription: 'Documents and laptop',
    itemQuantity: 2,
    itemWeight: 5,
    itemValue: 350000,
    isFragile: true,
    requiresSignature: true,
    billingType: 'PER_JOB',
    amount: 3500,
    paymentMethod: 'TRANSFER',
    isPaid: true,
    paidAt: `${today}T08:00:00Z`,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T07:30:00Z`, updatedBy: 'system' },
      { status: 'ASSIGNED', timestamp: `${today}T08:00:00Z`, updatedBy: 'dispatcher' },
      { status: 'ACCEPTED', timestamp: `${today}T08:05:00Z`, updatedBy: 'drv_002' },
      { status: 'PICKED_UP', timestamp: `${today}T09:15:00Z`, updatedBy: 'drv_002' },
      { status: 'IN_TRANSIT', timestamp: `${today}T09:20:00Z`, updatedBy: 'drv_002' },
      { status: 'DELIVERED', timestamp: `${today}T10:30:00Z`, updatedBy: 'drv_002' },
      { status: 'COMPLETED', timestamp: `${today}T10:35:00Z`, updatedBy: 'system' },
    ],
    pod: {
      id: 'pod_001',
      jobId: 'job_001',
      deliveredAt: `${today}T10:30:00Z`,
      receivedBy: 'Mrs. Williams',
      signatureData: 'BASE64_SIGNATURE_DATA',
      notes: 'Delivered to receptionist',
      createdAt: `${today}T10:30:00Z`,
    },
    customerName: 'TechCorp Nigeria',
    reference: 'TC-2024-001',
    createdBy: 'admin',
    createdAt: `${today}T07:30:00Z`,
    updatedAt: `${today}T10:35:00Z`,
    completedAt: `${today}T10:35:00Z`,
  },
  // In transit job
  {
    id: 'job_002',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-D4E5F6-ABC',
    jobType: 'PICKUP_DELIVERY',
    status: 'IN_TRANSIT',
    priority: 'HIGH',
    driverId: 'drv_001',
    driverName: 'Chukwuemeka Obi',
    vehicleId: 'veh_002',
    vehicleNumber: 'LAG-456-CD',
    assignedAt: `${today}T10:00:00Z`,
    acceptedAt: `${today}T10:02:00Z`,
    pickupAddress: '25 Marina Road, Lagos Island',
    pickupContactName: 'Dr. Adeyemi',
    pickupContactPhone: '08033333333',
    scheduledPickupTime: `${today}T11:00:00Z`,
    actualPickupTime: `${today}T11:10:00Z`,
    deliveryAddress: '88 Admiralty Way, Lekki Phase 1',
    deliveryLandmark: 'Beside The Palms Mall',
    deliveryContactName: 'Ms. Okonkwo',
    deliveryContactPhone: '08044444444',
    scheduledDeliveryTime: `${today}T12:30:00Z`,
    itemDescription: 'Medical samples (temperature controlled)',
    itemQuantity: 1,
    itemWeight: 2,
    itemValue: 150000,
    isFragile: true,
    requiresSignature: true,
    billingType: 'PER_JOB',
    amount: 5000,
    paymentMethod: 'PREPAID',
    isPaid: true,
    paidAt: `${today}T09:45:00Z`,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T09:30:00Z`, updatedBy: 'system' },
      { status: 'ASSIGNED', timestamp: `${today}T10:00:00Z`, updatedBy: 'dispatcher' },
      { status: 'ACCEPTED', timestamp: `${today}T10:02:00Z`, updatedBy: 'drv_001' },
      { status: 'EN_ROUTE_PICKUP', timestamp: `${today}T10:15:00Z`, updatedBy: 'drv_001' },
      { status: 'AT_PICKUP', timestamp: `${today}T11:00:00Z`, updatedBy: 'drv_001' },
      { status: 'PICKED_UP', timestamp: `${today}T11:10:00Z`, updatedBy: 'drv_001' },
      { status: 'IN_TRANSIT', timestamp: `${today}T11:15:00Z`, updatedBy: 'drv_001' },
    ],
    customerName: 'Lagos General Hospital',
    reference: 'LGH-LAB-0612',
    tags: ['medical', 'urgent', 'temperature-sensitive'],
    createdBy: 'admin',
    createdAt: `${today}T09:30:00Z`,
    updatedAt: `${today}T11:15:00Z`,
  },
  // At delivery job
  {
    id: 'job_003',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-G7H8I9-DEF',
    jobType: 'DELIVERY',
    status: 'AT_DELIVERY',
    priority: 'NORMAL',
    driverId: 'drv_003',
    driverName: 'Adebayo Ogundimu',
    vehicleId: 'veh_005',
    vehicleNumber: 'LAG-222-IJ',
    assignedAt: `${today}T09:30:00Z`,
    acceptedAt: `${today}T09:35:00Z`,
    pickupAddress: 'Shoprite, Ikeja City Mall',
    pickupContactName: 'Store Manager',
    pickupContactPhone: '08055555555',
    scheduledPickupTime: `${today}T10:30:00Z`,
    actualPickupTime: `${today}T10:45:00Z`,
    deliveryAddress: '12 Allen Avenue, Ikeja',
    deliveryLandmark: 'Near Computer Village',
    deliveryContactName: 'Mr. Emeka',
    deliveryContactPhone: '08066666666',
    scheduledDeliveryTime: `${today}T11:30:00Z`,
    itemDescription: 'Electronics and household items',
    itemQuantity: 5,
    itemWeight: 25,
    isFragile: true,
    requiresSignature: false,
    billingType: 'PER_JOB',
    amount: 4500,
    paymentMethod: 'COD',
    isPaid: false,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T09:00:00Z`, updatedBy: 'system' },
      { status: 'ASSIGNED', timestamp: `${today}T09:30:00Z`, updatedBy: 'dispatcher' },
      { status: 'ACCEPTED', timestamp: `${today}T09:35:00Z`, updatedBy: 'drv_003' },
      { status: 'PICKED_UP', timestamp: `${today}T10:45:00Z`, updatedBy: 'drv_003' },
      { status: 'IN_TRANSIT', timestamp: `${today}T10:50:00Z`, updatedBy: 'drv_003' },
      { status: 'AT_DELIVERY', timestamp: `${today}T11:25:00Z`, updatedBy: 'drv_003' },
    ],
    customerName: 'Home Delivery Customer',
    createdBy: 'api',
    createdAt: `${today}T09:00:00Z`,
    updatedAt: `${today}T11:25:00Z`,
  },
  // Freight job
  {
    id: 'job_004',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-J1K2L3-GHI',
    jobType: 'FREIGHT',
    status: 'IN_TRANSIT',
    priority: 'NORMAL',
    driverId: 'drv_004',
    driverName: 'Ibrahim Musa',
    vehicleId: 'veh_007',
    vehicleNumber: 'LAG-444-MN',
    assignedAt: `${today}T07:00:00Z`,
    acceptedAt: `${today}T07:10:00Z`,
    pickupAddress: 'Dangote Warehouse, Apapa',
    pickupContactName: 'Warehouse Supervisor',
    pickupContactPhone: '08077777777',
    scheduledPickupTime: `${today}T08:00:00Z`,
    actualPickupTime: `${today}T08:30:00Z`,
    deliveryAddress: 'Construction Site, Lekki-Epe Expressway',
    deliveryLandmark: 'After Ajah Underbridge',
    deliveryContactName: 'Site Engineer',
    deliveryContactPhone: '08088888888',
    scheduledDeliveryTime: `${today}T12:00:00Z`,
    itemDescription: 'Cement bags (100 units)',
    itemQuantity: 100,
    itemWeight: 5000,
    isFragile: false,
    requiresSignature: true,
    billingType: 'WEIGHT_BASED',
    amount: 75000,
    paymentMethod: 'TRANSFER',
    isPaid: true,
    paidAt: `${today}T06:00:00Z`,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T06:00:00Z`, updatedBy: 'system' },
      { status: 'ASSIGNED', timestamp: `${today}T07:00:00Z`, updatedBy: 'dispatcher' },
      { status: 'ACCEPTED', timestamp: `${today}T07:10:00Z`, updatedBy: 'drv_004' },
      { status: 'AT_PICKUP', timestamp: `${today}T08:00:00Z`, updatedBy: 'drv_004' },
      { status: 'PICKED_UP', timestamp: `${today}T08:30:00Z`, updatedBy: 'drv_004', note: 'Loading completed' },
      { status: 'IN_TRANSIT', timestamp: `${today}T08:45:00Z`, updatedBy: 'drv_004' },
    ],
    customerName: 'BuildRight Construction',
    reference: 'BRC-PO-2024-156',
    tags: ['freight', 'construction', 'heavy'],
    createdBy: 'admin',
    createdAt: `${today}T06:00:00Z`,
    updatedAt: `${today}T08:45:00Z`,
  },
  // Pending job (unassigned)
  {
    id: 'job_005',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-M4N5O6-JKL',
    jobType: 'PICKUP_DELIVERY',
    status: 'PENDING',
    priority: 'HIGH',
    pickupAddress: '5 Kofo Abayomi Street, VI',
    pickupContactName: 'Legal Secretary',
    pickupContactPhone: '08099999999',
    scheduledPickupTime: `${today}T14:00:00Z`,
    deliveryAddress: 'Federal High Court, Ikoyi',
    deliveryContactName: 'Court Clerk',
    deliveryContactPhone: '08011122233',
    scheduledDeliveryTime: `${today}T15:00:00Z`,
    itemDescription: 'Legal documents (confidential)',
    itemQuantity: 1,
    isFragile: false,
    requiresSignature: true,
    billingType: 'PER_JOB',
    amount: 6000,
    paymentMethod: 'TRANSFER',
    isPaid: false,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T11:00:00Z`, updatedBy: 'system' },
      { status: 'PENDING', timestamp: `${today}T11:00:00Z`, updatedBy: 'system' },
    ],
    customerName: 'Sterling Law Chambers',
    reference: 'SLC-COURT-0045',
    tags: ['legal', 'confidential', 'time-sensitive'],
    createdBy: 'api',
    createdAt: `${today}T11:00:00Z`,
    updatedAt: `${today}T11:00:00Z`,
  },
  // Express urgent job
  {
    id: 'job_006',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-P7Q8R9-MNO',
    jobType: 'DELIVERY',
    status: 'CREATED',
    priority: 'EXPRESS',
    pickupAddress: 'DHL Office, Airport Road',
    pickupContactName: 'DHL Agent',
    pickupContactPhone: '08044455566',
    scheduledPickupTime: `${today}T13:00:00Z`,
    deliveryAddress: '1 Adeola Odeku, VI',
    deliveryLandmark: 'Sterling Towers',
    deliveryContactName: 'CEO Office',
    deliveryContactPhone: '08077788899',
    scheduledDeliveryTime: `${today}T14:00:00Z`,
    itemDescription: 'International package (express)',
    itemQuantity: 1,
    itemWeight: 3,
    itemValue: 500000,
    isFragile: true,
    requiresSignature: true,
    billingType: 'PER_JOB',
    amount: 15000,
    paymentMethod: 'CARD',
    isPaid: true,
    paidAt: `${today}T12:30:00Z`,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T12:30:00Z`, updatedBy: 'api' },
    ],
    customerName: 'GlobalTech Inc.',
    reference: 'GT-EXP-2024-089',
    tags: ['express', 'international', 'vip'],
    createdBy: 'api',
    createdAt: `${today}T12:30:00Z`,
    updatedAt: `${today}T12:30:00Z`,
  },
  // Cancelled job
  {
    id: 'job_007',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-S1T2U3-PQR',
    jobType: 'DELIVERY',
    status: 'CANCELLED',
    priority: 'LOW',
    pickupAddress: '10 Ozumba Mbadiwe, VI',
    pickupContactName: 'Shop Assistant',
    pickupContactPhone: '08055566677',
    deliveryAddress: '20 Bode Thomas, Surulere',
    deliveryContactName: 'Mr. Customer',
    deliveryContactPhone: '08066677788',
    itemDescription: 'Fashion items',
    itemQuantity: 3,
    isFragile: false,
    requiresSignature: false,
    billingType: 'PER_JOB',
    amount: 2500,
    paymentMethod: 'COD',
    isPaid: false,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T08:00:00Z`, updatedBy: 'system' },
      { status: 'CANCELLED', timestamp: `${today}T09:00:00Z`, updatedBy: 'customer', note: 'Customer cancelled' },
    ],
    customerName: 'Fashion House',
    createdBy: 'api',
    createdAt: `${today}T08:00:00Z`,
    updatedAt: `${today}T09:00:00Z`,
  },
  // Failed delivery
  {
    id: 'job_008',
    tenantId: DEMO_TENANT_ID,
    jobNumber: 'JOB-V4W5X6-STU',
    jobType: 'DELIVERY',
    status: 'FAILED',
    priority: 'NORMAL',
    driverId: 'drv_002',
    driverName: 'Ngozi Eze',
    vehicleId: 'veh_001',
    vehicleNumber: 'LAG-123-AB',
    assignedAt: `${today}T07:00:00Z`,
    acceptedAt: `${today}T07:05:00Z`,
    pickupAddress: 'Konga Warehouse, Ogba',
    pickupContactName: 'Warehouse Staff',
    pickupContactPhone: '08077788800',
    actualPickupTime: `${today}T07:30:00Z`,
    deliveryAddress: '15 Wrong Address Street, Unknown',
    deliveryContactName: 'Unknown',
    deliveryContactPhone: '08011111199',
    itemDescription: 'E-commerce order',
    itemQuantity: 2,
    isFragile: false,
    requiresSignature: false,
    billingType: 'PER_JOB',
    amount: 2000,
    paymentMethod: 'COD',
    isPaid: false,
    logistics_delivery_status_history: [
      { status: 'CREATED', timestamp: `${today}T06:30:00Z`, updatedBy: 'system' },
      { status: 'ASSIGNED', timestamp: `${today}T07:00:00Z`, updatedBy: 'dispatcher' },
      { status: 'ACCEPTED', timestamp: `${today}T07:05:00Z`, updatedBy: 'drv_002' },
      { status: 'PICKED_UP', timestamp: `${today}T07:30:00Z`, updatedBy: 'drv_002' },
      { status: 'IN_TRANSIT', timestamp: `${today}T07:35:00Z`, updatedBy: 'drv_002' },
      { status: 'FAILED', timestamp: `${today}T08:30:00Z`, updatedBy: 'drv_002', note: 'Address not found' },
    ],
    pod: {
      id: 'pod_002',
      jobId: 'job_008',
      deliveredAt: `${today}T08:30:00Z`,
      receivedBy: 'N/A',
      exception: 'WRONG_ADDRESS',
      exceptionNotes: 'Address does not exist. Customer unreachable.',
      createdAt: `${today}T08:30:00Z`,
    },
    customerName: 'Online Shopper',
    createdBy: 'api',
    createdAt: `${today}T06:30:00Z`,
    updatedAt: `${today}T08:30:00Z`,
  },
];

// ============================================================================
// DEMO STATISTICS
// ============================================================================

export const DEMO_STATS = {
  vehicles: {
    total: 10,
    available: 3,
    inUse: 4,
    maintenance: 1,
    outOfService: 1,
    reserved: 1,
  },
  drivers: {
    total: 6,
    available: 1,
    onTrip: 3,
    offDuty: 1,
    suspended: 1,
  },
  jobs: {
    total: 8,
    active: 4,
    completed: 1,
    pending: 2,
    cancelled: 1,
    failed: 1,
  },
  today: {
    deliveries: 5,
    revenue: 106000,
    averageDeliveryTime: 45, // minutes
  },
};

// ============================================================================
// STORE GETTERS
// ============================================================================

export function getVehiclesStore(): Vehicle[] {
  if (vehiclesStore.length === 0) {
    vehiclesStore = [...DEMO_VEHICLES];
  }
  return vehiclesStore;
}

export function getDriversStore(): Driver[] {
  if (driversStore.length === 0) {
    driversStore = [...DEMO_DRIVERS];
  }
  return driversStore;
}

export function getJobsStore(): Job[] {
  if (jobsStore.length === 0) {
    jobsStore = [...DEMO_JOBS];
  }
  return jobsStore;
}

export function getPODStore(): ProofOfDelivery[] {
  if (podStore.length === 0) {
    // Extract PODs from jobs
    DEMO_JOBS.forEach(job => {
      if (job.pod) {
        podStore.push(job.pod);
      }
    });
  }
  return podStore;
}

export function resetDemoData(): void {
  vehiclesStore = [...DEMO_VEHICLES];
  driversStore = [...DEMO_DRIVERS];
  jobsStore = [...DEMO_JOBS];
  podStore = [];
  getPODStore(); // Re-populate PODs
}
